export const LANGUAGE_MAP = new Map<String, { abbreviation: String; color: String }>([
  // TODO: ADD MORE LANGUAGES
  // https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes#:~:text=ISO%20639%20is%20a%20standardized,later%20versions%20of%20the%20nomenclature.
  ["English", { abbreviation: "ENG", color: "#1DF06E" }],
  ["Chinese", { abbreviation: "CHI", color: "#F851FA" }],
  ["Spanish", { abbreviation: "SPA", color: "#27B1D4" }],
  ["Hindi", { abbreviation: "HIN", color: "#BCD98E" }],
  ["Arabic", { abbreviation: "ARA", color: "#59B4E7" }],
  ["Portuguese", { abbreviation: "POR", color: "#EC1074" }],
  ["Bengali", { abbreviation: "BEN", color: "#69B7AE" }],
  ["Russian", { abbreviation: "RUS", color: "#DF2A57" }],
  ["Japanese", { abbreviation: "JAP", color: "#D711F9" }],
  ["Punjabi", { abbreviation: "PUN", color: "#224CB4" }],
  ["French", { abbreviation: "FRE", color: "#33E56B" }],
  ["German", { abbreviation: "GER", color: "#DDE784" }],
  ["Italian", { abbreviation: "ITA", color: "#538E95" }],
  ["Dutch", { abbreviation: "DUT", color: "#55FBAD" }],
  ["Swedish", { abbreviation: "SWE", color: "#701AA7" }],
  ["Polish", { abbreviation: "POL", color: "#28EC5C" }],
  ["Greek", { abbreviation: "GRE", color: "#F78FF2" }],
  ["Romanian", { abbreviation: "ROM", color: "#5FEC4D" }],
  ["Spanish", { abbreviation: "SPA", color: "#BCF5E3" }],
  ["Portuguese", { abbreviation: "POR", color: "#D10E21" }],
  ["Chinese", { abbreviation: "CHI", color: "#B243EF" }],
  ["Hindi", { abbreviation: "HIN", color: "#4EDEA8" }],
  ["Bengali", { abbreviation: "BEN", color: "#EDA47A" }],
  ["Japanese", { abbreviation: "JAP", color: "#16F039" }],
  ["Punjabi", { abbreviation: "PUN", color: "#D79213" }],
  ["Telugu", { abbreviation: "TEL", color: "#95F4BC" }],
  ["Marathi", { abbreviation: "MAR", color: "#6B526D" }],
  ["Tamil", { abbreviation: "TAM", color: "#639EDE" }],
  ["Urdu", { abbreviation: "URD", color: "#68B306" }],
  ["Turkish", { abbreviation: "TUR", color: "#DDC62D" }],
  ["Swahili", { abbreviation: "SWA", color: "#21B8BE" }],
  ["Hausa", { abbreviation: "HAU", color: "#D69E9F" }],
  ["Yoruba", { abbreviation: "YOR", color: "#8CEAB8" }],
  ["Amharic", { abbreviation: "AMH", color: "#FEFF2B" }],
  ["Zulu", { abbreviation: "ZUL", color: "#C5D290" }],
  ["Igbo", { abbreviation: "IGB", color: "#AA2CB9" }],
  ["Shona", { abbreviation: "SHO", color: "#575931" }],
  ["Somali", { abbreviation: "SOM", color: "#72D6E0" }],
  ["Fulfulde", { abbreviation: "FUL", color: "#C6A6A1" }],
  ["Tigrinya", { abbreviation: "TIG", color: "#11BCA5" }],
  ["Arabic", { abbreviation: "ARA", color: "#53B50B" }],
  ["Persian (Farsi)", { abbreviation: "PER", color: "#2CEB14" }],
  ["Turkish", { abbreviation: "TUR", color: "#EFEE5B" }],
  ["Hebrew", { abbreviation: "HEB", color: "#DAEC63" }],
  ["Kurdish", { abbreviation: "KUR", color: "#D4156D" }],
  ["Quechua", { abbreviation: "QUE", color: "#BC1159" }],
  ["Maori", { abbreviation: "MAO", color: "#7153B5" }],
  ["Ainu", { abbreviation: "AIN", color: "#91CD2B" }],
  ["Navajo", { abbreviation: "NAV", color: "#6F55CE" }],
]);
